Repository source-academy/frontend, pull requests merged in 2024-03, with the labels that each got.

#2853 CSE Machine: Rewrite the Config enum to be a constant object
  src/features/cseMachine/CseMachineConfig.ts
  src/features/cseMachine/CseMachineControlStashConfig.ts
  src/features/cseMachine/CseMachineLayout.tsx
  src/features/cseMachine/CseMachineUtils.ts
  src/features/cseMachine/animationComponents/AnimationComponents.tsx
  src/features/cseMachine/components/ArrayNullUnit.tsx
  src/features/cseMachine/components/ArrayUnit.tsx
  src/features/cseMachine/components/ControlItemComponent.tsx
  src/features/cseMachine/components/ControlStack.tsx
  src/features/cseMachine/components/Frame.tsx
  src/features/cseMachine/components/StashItemComponent.tsx
  src/features/cseMachine/components/Text.tsx
  src/features/cseMachine/components/arrows/GenericArrow.tsx
  src/features/cseMachine/components/values/FnValue.tsx
  src/features/cseMachine/components/values/GlobalFnValue.tsx
  src/features/cseMachine/components/values/UnassignedValue.tsx
Labels: _refactor

#2847 CSE Machine: Enable visualization when running programs with runtime errors
  src/commons/sagas/WorkspaceSaga.ts
  src/commons/sideContent/__tests__/__snapshots__/SideContentCseMachine.tsx.snap
  src/commons/sideContent/content/SideContentCseMachine.tsx
  src/pages/playground/__tests__/__snapshots__/Playground.tsx.snap
Labels: Enhancement

#2834 Implement read-only option to playground sessions
  src/commons/application/ApplicationTypes.ts
  src/commons/assessmentWorkspace/AssessmentWorkspace.tsx
  src/commons/collabEditing/CollabEditingActions.ts
  src/commons/collabEditing/CollabEditingHelper.ts
  src/commons/collabEditing/CollabEditingTypes.ts
  src/commons/controlBar/ControlBarSessionButton.tsx
  src/commons/editingWorkspace/EditingWorkspace.tsx
  src/commons/editor/Editor.tsx
  src/commons/editor/UseShareAce.tsx
  src/commons/editor/__tests__/Editor.tsx
  src/commons/editor/__tests__/__snapshots__/Editor.tsx.snap
  src/commons/workspace/WorkspaceReducer.ts
  src/commons/workspace/WorkspaceTypes.ts
  src/pages/academy/grading/subcomponents/GradingWorkspace.tsx
  src/pages/playground/Playground.tsx
Labels: blocked

#2869 CSE Machine: Implement navigation arrows to jump to the next/previous change in environment (frontend)
  src/commons/application/ApplicationTypes.ts
  src/commons/sagas/WorkspaceSaga/helpers/evalCode.ts
  src/commons/sagas/__tests__/PlaygroundSaga.ts
  src/commons/sideContent/content/SideContentCseMachine.tsx
  src/commons/workspace/WorkspaceActions.ts
  src/commons/workspace/WorkspaceReducer.ts
  src/commons/workspace/WorkspaceTypes.ts
  src/commons/workspace/__tests__/WorkspaceReducer.ts
Labels: Enhancement, blocked

#2863 Assessment Configurability in Ground Control
  src/commons/XMLParser/XMLParserHelper.ts
  src/commons/application/actions/__tests__/SessionActions.ts
  src/commons/application/reducers/__tests__/SessionReducer.ts
  src/commons/assessment/AssessmentTypes.ts
  src/commons/assessment/__tests__/Assessment.tsx
  src/commons/assessmentWorkspace/AssessmentWorkspace.tsx
  src/commons/assessmentWorkspace/__tests__/AssessmentWorkspace.tsx
  src/commons/mocks/AssessmentMocks.ts
  src/commons/profile/__tests__/Profile.tsx
  src/commons/sagas/BackendSaga.ts
  src/commons/sagas/RequestsSaga.ts
  src/commons/sagas/__tests__/BackendSaga.ts
  src/features/groundControl/GroundControlActions.ts
  src/features/groundControl/GroundControlTypes.ts
  src/pages/academy/adminPanel/subcomponents/assessmentConfigPanel/AssessmentConfigPanel.tsx
  src/pages/academy/groundControl/GroundControl.tsx
  src/pages/academy/groundControl/GroundControlContainer.ts
  src/pages/academy/groundControl/subcomponents/GroundControlConfigureCell.tsx
  src/styles/_academy.scss
  src/styles/_groundcontrol.scss
Labels: blocked

#2831 Cslang
  craco.config.js
  package.json
  src/commons/application/ApplicationTypes.ts
  src/commons/editor/Editor.tsx
  src/commons/navigationBar/subcomponents/NavigationBarLangSelectButton.tsx
  src/commons/sagas/WorkspaceSaga/helpers/evalCode.ts
  src/commons/utils/AceHelper.ts
  src/commons/utils/CToWasmHelper.ts
  yarn.lock
Labels: Enhancement
